name: Test

run-name: Test workflows

on: workflow_dispatch

jobs:
    test:
        runs-on: [ubuntu-latest]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Test Custom Action
              uses: iaeshliman/semantic-version@latest
